### ISSUE TITLE
`ses_gender_male` ou `ses_gender_female`, variable binaire

### ISSUE THREAD

**Issue by hubcad25** [clessn/datagotchi_federal_2024#1]
En plus de `ses_gender_factor`, il faudrait une variable où 1 == male et le reste 0 (ou la même chose avec female).

Raison: quand on fait un modèle de régression, les catégories qui n'ont pas beaucoup d'observations vont avoir des marges d'erreur énormes.

**Comment by capel201** [comment]
C boulé boule!
